name: Android Release Build

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          build-tools: "34.0.0"

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build Release APKs (unsigned, con splits por ABI)
        run: ./gradlew assembleRelease

      - name: Decode keystore
        run: echo "$ANDROID_KEYSTORE_BASE64" | base64 -d > freyja.jks
        env:
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}

      - name: Sign split APKs
        run: |
          mkdir -p dist
          shopt -s nullglob
          for f in app/build/outputs/apk/release/*-release-unsigned.apk; do
            echo "Firmando: $f"
            jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 \
              -keystore freyja.jks \
              -storepass "${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" \
              -keypass "${{ secrets.ANDROID_KEY_PASSWORD }}" \
              "$f" "${{ secrets.ANDROID_KEY_ALIAS }}"
            signed="${f/-unsigned/}"   # quita sufijo -unsigned
            mv "$f" "$signed"

            base="$(basename "$signed")"
            if [[ "$base" == *"arm64-v8a"* ]]; then
              cp "$signed" dist/freyja-arm64-v8a.apk
            elif [[ "$base" == *"armeabi-v7a"* ]]; then
              cp "$signed" dist/freyja-armeabi-v7a.apk
            elif [[ "$base" == *"x86_64"* ]]; then
              cp "$signed" dist/freyja-x86_64.apk
            else
              cp "$signed" "dist/$base"
            fi
          done
          ls -lh dist

      - name: Verify signatures
        run: |
          for a in dist/*.apk; do
            echo "Verificando: $a"
            jarsigner -verify "$a"
          done

      - name: Upload Signed APKs (artifacts)
        uses: actions/upload-artifact@v4
        with:
          name: freyja-release-splits
          path: dist/*.apk
          retention-days: 7

  github_release:
    needs: build
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Download signed APK artifacts
        uses: actions/download-artifact@v4
        with:
          name: freyja-release-splits
          path: dist

      - name: Create GitHub Release (attach all APKs)
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.apk
          name: "🌌 Freyja ${{ github.ref_name }} — Guardia Activa"
          body: |
            ⚔️ **Invocación completada**
            Versión `${{ github.ref_name }}` con APKs por arquitectura:

            - **arm64-v8a** → `freyja-arm64-v8a.apk`
            - **armeabi-v7a** → `freyja-armeabi-v7a.apk`
            - **x86_64** → `freyja-x86_64.apk`

            Incluye optimizaciones de compilación (Java/Kotlin 17), splits por ABI y firma automática.
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}