- name: Print Android env
  run: |
    echo "JAVA_HOME=$JAVA_HOME"
    echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT"
    sdkmanager --list | head -n 50 || true
    cmake --version || true
    ndk-build --version || true
    echo "---- tree app/src/main/cpp ----"
    ls -la app/src/main/cpp || true
    echo "---- CMakeLists.txt ----"
    cat app/src/main/cpp/CMakeLists.txt || true

- name: Purge Gradle caches
  run: |
    rm -rf ~/.gradle/caches/* ~/.gradle/daemon/* || true
    rm -rf ~/.android/build-cache || true
    echo "Caches purgadas"

- name: Compile Kotlin (debug) — capture logs
  run: |
    set -e
    ./gradlew --no-daemon --stacktrace --info --no-parallel --max-workers=1 :app:compileDebugKotlin 2>&1 | tee kotlindebug.log
    echo "--- Kotlin errors (first 60) ---"
    grep -n "^e: " kotlindebug.log | head -n 60 || true

- name: Upload Kotlin log
  uses: actions/upload-artifact@v4
  with:
    name: kotlindebug-log
    path: kotlindebug.log

- name: Assemble Release (APK + AAB) with verbose logs
  env:
    GRADLE_OPTS: -Xmx6g
    ANDROID_KEYSTORE_PATH: ${{ github.workspace }}/keystore.jks
    ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
    ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
    ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
    API_BASE_URL: ${{ secrets.API_BASE_URL }}
  run: |
    ./gradlew --version
    ./gradlew --no-daemon --stacktrace --info --warning-mode=all \
      :app:assembleRelease :app:bundleRelease
