name: Build Freyja Beta
on:
  workflow_dispatch:
  push: { branches: [ main ] }
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { distribution: temurin, java-version: 17 }
      - uses: android-actions/setup-android@v3
        with: { api-level: 34, build-tools: "34.0.0" }
      - run: gradle wrapper --gradle-version 8.7 --distribution-type all
      - run: ./gradlew :app:assembleDebug
      - uses: actions/upload-artifact@v4
        with:
          name: Freyja-Beta-0.9-debug
          path: app/build/outputs/apk/debug/*.apk
          if-no-files-found: error
