name: Android Release (signed)

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-22.04
    env:
      # <- Secrets disponibles como variables de entorno
      API_BASE_URL: ${{ secrets.API_BASE_URL }}
      BACKUP_PASSPHRASE: ${{ secrets.BACKUP_PASSPHRASE }}
      ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
      ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
      ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
      ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
      RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          build-tools: "34.0.0"
          ndk: 26.3.11579264
          cmake: "3.22.1"

      - name: Create local.properties
        run: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
          cat local.properties

      # ---------- LOGIN con RELEASE_TOKEN (gh) ----------
      - name: Login to GitHub CLI (gh)
        run: |
          echo "$RELEASE_TOKEN" | gh auth login --with-token
          gh auth status

      # ---------- Restaurar keystore desde Base64 ----------
      - name: Restore Android keystore
        run: |
          echo "$ANDROID_KEYSTORE_BASE64" | base64 -d > freyja-release.keystore
          ls -l freyja-release.keystore

      # ---------- Opcional: ajustar memoria/flags Gradle ----------
      - name: Gradle Info
        run: ./gradlew --no-daemon --version

      - name: Clean
        run: ./gradlew --no-daemon clean

      # ---------- Build Release firmado ----------
      - name: Assemble Release (signed)
        env:
          ANDROID_KEYSTORE_PATH: ${{ github.workspace }}/freyja-release.keystore
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
          API_BASE_URL: ${{ secrets.API_BASE_URL }}
          BACKUP_PASSPHRASE: ${{ secrets.BACKUP_PASSPHRASE }}
        run: |
          ./gradlew --no-daemon --stacktrace --info --no-parallel --max-workers=1 \
            :app:assembleRelease

      - name: Upload signed APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-signed
          path: app/build/outputs/apk/release/*.apk

      # ---------- Crear/actualizar Release en GitHub ----------
      - name: Create GitHub Release and upload APK
        env:
          TAG: ${{ github.ref_name }}
        run: |
          gh release view "$TAG" >/dev/null 2>&1 || gh release create "$TAG" -t "Freyja $TAG" -n "Autogenerated release"
          gh release upload "$TAG" app/build/outputs/apk/release/*.apk --clobber