name: Android Debug Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - name: Set up Android SDK (base)
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 10406996
          accept-android-sdk-licenses: true
          log-accepted-android-sdk-licenses: true

      - name: Install required Android packages
        shell: bash
        run: |
          set -euxo pipefail
          SDKROOT="${ANDROID_HOME:-$ANDROID_SDK_ROOT}"
          SDKMAN="$SDKROOT/cmdline-tools/latest/bin/sdkmanager"
          yes | "$SDKMAN" --licenses > /dev/null || true
          "$SDKMAN" --install "platform-tools" "platforms;android-34" "build-tools;34.0.0"
