name: Build Freyja Beta
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # Si NO subes keystore, compila Debug; si subes secretos, compila Release firmado
      - name: Build (Debug or Release)
        run: |
          if [ -n "${{ secrets.KEYSTORE_BASE64 }}" ]; then
            echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > freyja.keystore
            ./gradlew assembleRelease \
              -Pandroid.injected.signing.store.file=freyja.keystore \
              -Pandroid.injected.signing.store.password="${{ secrets.KEYSTORE_PASSWORD }}" \
              -Pandroid.injected.signing.key.alias="${{ secrets.KEY_ALIAS }}" \
              -Pandroid.injected.signing.key.password="${{ secrets.KEY_PASSWORD }}"
          else
            ./gradlew assembleDebug --no-daemon
          fi

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Freyja-APK
          path: |
            app/build/outputs/apk/debug/*.apk
            app/build/outputs/apk/release/*.apk
          if-no-files-found: warn