name: Android Release

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
      ANDROID_KEY_ALIAS:         ${{ secrets.ANDROID_KEY_ALIAS }}
      ANDROID_KEY_PASSWORD:      ${{ secrets.ANDROID_KEY_PASSWORD }}
      ANDROID_KEYSTORE_BASE64:   ${{ secrets.ANDROID_KEYSTORE_BASE64 }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # Opcional: instala toolchains base; Gradle descargará lo que falte.
      - name: Install base SDK packages
        run: |
          sdkmanager "platform-tools" "build-tools;34.0.0" "platforms;android-34"

      - name: Decode keystore
        run: echo "$ANDROID_KEYSTORE_BASE64" | base64 -d > freyja-release.keystore

      - name: Create local.properties
        run: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Assemble Release (signed)
        run: ./gradlew --no-daemon assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/apk/release/*.apk
          if-no-files-found: error