name: Android Release Build

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          build-tools: "34.0.0"

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Decode keystore
        run: |
          echo "$KEYSTORE_BASE64" | base64 -d > freyja.jks
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Sign APK
        run: |
          jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 \
            -keystore freyja.jks \
            -storepass ${{ secrets.KEY_PASSWORD }} \
            app/build/outputs/apk/release/app-release-unsigned.apk \
            ${{ secrets.KEY_ALIAS }}

      - name: Verify Signature
        run: jarsigner -verify app/build/outputs/apk/release/app-release-unsigned.apk

      - name: Rename signed APK
        run: mv app/build/outputs/apk/release/app-release-unsigned.apk freyja-release.apk

      - name: Upload Signed APK
        uses: actions/upload-artifact@v4
        with:
          name: freyja-release
          path: freyja-release.apk