name: Android Release (signed)

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  contents: read

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

env:
  JAVA_VERSION: '17'
  ANDROID_NDK_VERSION: '26.3.11579264'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}

      - name: Set up Android SDK + NDK
        uses: android-actions/setup-android@v3
        with:
          packages: |
            platforms;android-34
            build-tools;34.0.0
            platform-tools
            ndk;${{ env.ANDROID_NDK_VERSION }}

      - name: Gradle wrapper preflight
        shell: bash
        run: |
          chmod +x gradlew || true
          echo "Wrapper perms:"
          ls -l gradlew || true
          echo "Wrapper dir:"
          ls -l gradle/wrapper || true

      - name: Restore keystore
        shell: bash
        env:
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
        run: |
          echo "$ANDROID_KEYSTORE_BASE64" | base64 -d > freyja-release.keystore
          echo "ANDROID_KEYSTORE_PATH=${{ github.workspace }}/freyja-release.keystore" >> $GITHUB_ENV

      - name: Gradle properties for CI
        shell: bash
        run: |
          cat > gradle.properties <<'EOF'
          org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
          org.gradle.parallel=false
          org.gradle.workers.max=1
          android.useAndroidX=true
          android.enableJetifier=true
          android.enableParallelResourceProcessing=false
          android.aapt2ThreadPoolSize=1
          EOF
          cat gradle.properties

      # ============ BUILD CON CAPTURA DE LOGS SIEMPRE ============
      - name: Build (assembleRelease) con logs robustos
        shell: bash
        env:
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS:        ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD:     ${{ secrets.ANDROID_KEY_PASSWORD }}
          API_BASE_URL:             ${{ secrets.API_BASE_URL }}
          BACKUP_PASSPHRASE:        ${{ secrets.BACKUP_PASSPHRASE }}
        run: |
          set +e
          mkdir -p ci-logs
          : > ci-logs/02-assembleRelease.log
          : > ci-logs/env.txt
          echo "PWD=$(pwd)" >> ci-logs/env.txt
          echo "JAVA_HOME=$JAVA_HOME" >> ci-logs/env.txt
          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> ci-logs/env.txt
          echo "ls gradlew:" >> ci-logs/env.txt
          ls -l gradlew >> ci-logs/env.txt || true
          echo "ls gradle/wrapper:" >> ci-logs/env.txt
          ls -l gradle/wrapper >> ci-logs/env.txt || true

          ./gradlew --version | tee ci-logs/00-gradle-version.txt || true
          ./gradlew --no-daemon clean | tee ci-logs/01-clean.log || true

          (
            ./gradlew --no-daemon --stacktrace --info --console=plain \
              -Dorg.gradle.logging.stacktrace=all \
              -Pandroid.injected.signing.store.file="${ANDROID_KEYSTORE_PATH}" \
              -Pandroid.injected.signing.store.password="${ANDROID_KEYSTORE_PASSWORD}" \
              -Pandroid.injected.signing.key.alias="${ANDROID_KEY_ALIAS}" \
              -Pandroid.injected.signing.key.password="${ANDROID_KEY_PASSWORD}" \
              :app:assembleRelease
          ) > >(tee -a ci-logs/02-assembleRelease.log) 2> >(tee -a ci-logs/02-assembleRelease.log >&2)

          echo $? > ci-logs/exitcode.txt
          set -e
        continue-on-error: true

      - name: Recopilar reportes y salidas
        if: always()
        shell: bash
        run: |
          mkdir -p ci-logs/buckets
          cp -R app/build/outputs ci-logs/buckets/outputs 2>/dev/null || true
          cp -R app/build/reports ci-logs/buckets/reports 2>/dev/null || true
          cp -R app/build/intermediates/merged_manifests ci-logs/buckets/manifests 2>/dev/null || true
          cp -R app/build/intermediates/cxx ci-logs/buckets/cxx 2>/dev/null || true

          {
            echo "===== Kotlin errors (e:) ====="
            grep -n "^e: " ci-logs/02-assembleRelease.log || true
            echo
            echo "===== AAPT2 / Android resource linking ====="
            grep -n "AAPT2" ci-logs/02-assembleRelease.log || true
            grep -n "Android resource linking failed" -R ci-logs/buckets/reports 2>/dev/null || true
            echo
            echo "===== FAILED TASKS ====="
            grep -n "FAILED" ci-logs/02-assembleRelease.log || true
            echo
            echo "===== Stacktraces breves ====="
            grep -n "at org.gradle" ci-logs/02-assembleRelease.log | head -n 200 || true
          } > ci-logs/SUMMARY.txt

      - name: Subir artifact de logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: ci-logs
          if-no-files-found: warn
          compression-level: 6
